language: java

env:
  global:
    - secure: "FH7mbd2G731bzhY8WM9y33J6Tyh3G+oNU4CesijLevMRZNbD207DPvGJ9l7mecQptBNDEfdrJXT2Tbht81RCoAVkKTZwFdDXkafcGUyfZkz5jpTCP3XHY6+q61zN5phtEMXChtluLERIr/ZciPhnYxmRFKzrvoqfkuVxbPCE/8RwVfNs+iK3H12d0MCM5eQvSW2z651Ry6PkFkF4noTvUYh3zcC4s+bq4EhJ/VE9VnV3CrilhJJPhzCn+zHT3Y1DG6eGNV/cDEwlfgn0wjdoYdpVmAUR4QWRwvoNKp0pMxcLN9ai53NSIj4sTv8rA9KjEBBJIt2rNwcQLMWodbVSPcWZipvhoO41opDJ2GIQTL46vZBSbYZYHgwMNk6327MYVhDg9DLm/SnNMRDJjU2+fFdZjNgBiorZogganRDju+I1giFOKZjbqOe8UB1Nt74gO6O3r6YFj8NbdRy57E0M8uAUi0f+9OxSnA/HeUBWFVc4lODnBaohstnx3lM7XjFTJZqa4YcBEQjfbcKBiG2A69/r09GIHLZk0EemQLq7h4dqHKdAoBhRyWqREYTegFmxGxcEjhKjyju/n5FpB/9HeAeGuqFNoG++SzVHZxR74YAf99xrfMrdUUIR0piYlSTVTHtR7gl6DZpBxNn8UzJ+5IFkva77FG7KXnrJoJob5v8="
    - secure: "T35k47+4DcUB5JJfEeyA+vNoYQ4bR/XTP6feaDH3b6/J+2FvcmvkSwmUCHav6BeL/G4T3A7xshy8VTPK4g7UkUWa3MaMbtQzKCMlqFn1aRFLlJuhxrN3yG3vJ42jxx0TtACUrGhxRyjZIET79MUgIQXcnpOBE7Behf6XINQ0bp5BTXJfs3tTEcNMI6l7eylSe1i3lBjRhVGC1gehPjp24xogd2P0BZRsJeuLxDORTtQK1+LJD9b3PqDUmFmN3huNtxFr7EmT6ozZn3SlzfCz/iZSAHLMZ5Moe48wENLOPV5Aaby6lcUZEVmk3uVamdVNdPORjpKleu5yiYsCMwf8NOAg+QWXd3kzR5qhEzi4LkI/t05Coe2w8Wj3NYke/vEBuCe8LoK6wceewp0isAhNSuA1VdxKwpdtFeE41RHX0LNhRa2HszvFxW41xwEattiIbRPwg/cZKDFq3WCKoeE93gUyRud3SEKt5GUSOrnLC9cQqEusdY1LR/Ue4INwtyLMsCIHES8OrW+chIp0P8DOJJpI+PH3iqjoLeQ3IMLFdXHBbImGnuogAEqW8ni0/qIAKorcvAc+XZB+yBL7YViloeAUXzFNtvP8/dX0xM/VqbyKTiDlv+9fp9hDm998O+N3fMU7l0uSY81meG4YtKTMhOKOcBD9zN47vr/EOFbmG3Y="

sudo: false

jdk:
  - oraclejdk8


os:
  - linux

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean build publishPlugins  -Pgradle.publish.key=$key -Pgradle.publish.secret=$secret -i --continue
