language: java

env:
  global:
    - secure: "e1BVlVEnmR4EVz7DXNG2KNOPSoUJAEl7YM3HvkCZfTOs0Ohp30PAxuNyQyRz/r9QdT6nilvmIlvVvUuSh1R0kST6rzzAm9k7YPDlUjlXwU14eClj5v4aqC5BZWwsszuhpSvdeRwDWIxUAf0+XNIUdQ0GQyFEJJIzNf7FrMaiUdZF4Q7noAEXy6+vbTdVe/6q8q1i1kKYZBoiwF4DISuubtwh4dqhJDby3WYU91ZP4cB+UTAfxK1baw3Y6VBWbS3KI5EOADgHz5DPqheKDcN4MgHg5+M4ooxw95mEvq0N8YRHam7Z90/Vz/VyRXzV5ry0wQ2mfLG0W1YSyf34rauhWRn30Ut67bLq+xAS3qSahNqjJVIj7fkaRXROO89/4l/FpBJOLTjSg5VJMAARe3OsfrqUf0J1xnAC8nWK+CQX4UoYuhvwFUrbD1s7OxAUa0uQYkYvLtXsQUyOvX4nzM5eYlI9WwECLQxDHr9gGQO2Dte1DGR9+bXCn2EO5QSigUQvRn919ha/iOafq7opw9xulJB0HEgt39LSQP4j2Iw+biCX4RE1/p7UBjGW7XbQj4+pmDL26T6ik6qieogElZ7yErPXlL2vl09J3YfQb3f3WFU9FRIxvbuncLBBikH4AoHodV89syW8oOugD15bj52bKqa9h6pbse7PJjYXfvSlu2s="
    - secure: "Ms/KTqQNFqi/EmUEpMsCXTHtAi+NILdGkMASvw5uKRVo2L07j3r9KJ92y2SWH3/ycI5N5Qzp2+8XJ62BOhDUwDLZ5BsSnIeVNF74FrycFxiDAU625qQsHaxrzD6u3ovRqNlYXklbuCFBTceujPj9CRUet31Yq8IxPKSP6T0iZCphYVvVVI0L3Au98m+Jxwv6WgVv4Z50n9QUs6AmKid0EAskkY63Z9WjYdCuNaXNwMfflTpEavBjxe3tdxpYQnsMLKWkvVcL+GRXJtVyky6NHGeXSzISo4Josv9HsBpyfJQ/vH5S8Fp8bhKdh1fU2WjdNOuD81hZRQZBD2a6wcjj1WKOX3CBEZLqiXkH/tTi7W9AeU2dVrxZMQad17ElcVdPxvI8Aq6vad0MI9ymi/8Y4jMCbpYZqZPy927FMFus3seHOAYlzWbNXODDJ78f8nh6oyUueNIGvTfvbTs1j3vMXYz09o9/xDJcOLYSK7jXzebjS0Zp/iadg/XvydV9YhMv++MLXXZ/5PCD3Rgv0TWJGy6KizY9qUp53UoJRxThBY8+thQkEBjhdCW/Rb+wYOpROErWDCFUBczDkVmu383E447I7MxJOWouBp0Mat7VtnCFYdPC2hHP3DL3Iq6DcdSplDeC2ddd7nf0Hh+JvczNUqxwXeDGv5rZr4poAFPl3U4="

sudo: false

jdk:
  - oraclejdk8


os:
  - linux

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean build publishPlugins  -Pgradle.publish.key=${gradle.publish.key} -Pgradle.publish.secret=${gradle.publish.secret} -i --continue
